# Generated by Django 4.2.5 on 2023-09-06 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='TipoPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Tipo de Pessoa',
                'verbose_name_plural': 'Tipos de Pessoa',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('nome', models.CharField(default='Usuário', max_length=255)),
                ('tipopessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ifbucks.tipopessoa')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifbucks.categoria')),
            ],
            options={
                'verbose_name': 'Tipo de Produto',
                'verbose_name_plural': 'Tipos de Produtos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nome', models.CharField(max_length=250)),
                ('descricao', models.CharField(default='aa', max_length=255)),
                ('imagem', models.ImageField(blank=True, upload_to='prduto/%Y/%m/%d/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifbucks.categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField(default=1)),
                ('status', models.BooleanField()),
                ('hora_pedido', models.TimeField()),
                ('usuario_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifbucks.usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('pedido_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ifbucks.pedido')),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ifbucks.produto')),
            ],
            options={
                'verbose_name': 'Item Pedido',
                'verbose_name_plural': 'Itens Pedido',
            },
        ),
    ]
