# Generated by Django 4.2.4 on 2023-08-21 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField(default=0)),
                ('status', models.BooleanField()),
                ('hora_pedido', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nome', models.CharField(max_length=250)),
                ('descricao', models.CharField(default='1000', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TiposProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('tipopessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifbucks.tipopessoa')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tiposprodutos',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_tipoproduto_id'),
        ),
        migrations.AddConstraint(
            model_name='tipopessoa',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_tipopessoa_id'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='tipoProduto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifbucks.tiposprodutos'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifbucks.usuario'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifbucks.pedidos'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifbucks.produtos'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('cpf', 'id'), name='unique_usuario_cpf_id'),
        ),
        migrations.AddConstraint(
            model_name='produtos',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_produto_id'),
        ),
        migrations.AddConstraint(
            model_name='pedidos',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_pedido_id'),
        ),
    ]
