# Generated by Django 4.2.4 on 2023-08-27 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidos',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='tipopessoa',
            options={'verbose_name': 'Tipo de Pessoa', 'verbose_name_plural': 'Tipos de Pessoa'},
        ),
        migrations.AlterModelOptions(
            name='tiposprodutos',
            options={'verbose_name': 'Tipo de Produto', 'verbose_name_plural': 'Tipos de Produtos'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
