# Generated by Django 4.2.5 on 2023-09-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbucks', '0002_remove_categoria_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nome',
            field=models.CharField(default='Categoria', max_length=100),
        ),
    ]
