# Generated by Django 4.2.4 on 2023-09-01 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbucks', '0002_alter_pedidos_options_alter_produtos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField(default=1)),
                ('status', models.BooleanField()),
                ('hora_pedido', models.TimeField()),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produto',
        ),
        migrations.RenameModel(
            old_name='TiposProdutos',
            new_name='TipoProduto',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item Pedido', 'verbose_name_plural': 'Itens Pedido'},
        ),
        migrations.RemoveConstraint(
            model_name='produto',
            name='unique_produto_id',
        ),
        migrations.RemoveConstraint(
            model_name='tipopessoa',
            name='unique_tipopessoa_id',
        ),
        migrations.RemoveConstraint(
            model_name='tipoproduto',
            name='unique_tipoproduto_id',
        ),
        migrations.RemoveConstraint(
            model_name='usuario',
            name='unique_usuario_cpf_id',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='produto',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='produto_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ifbucks.produto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipopessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ifbucks.tipopessoa'),
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifbucks.usuario'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ifbucks.pedido'),
            preserve_default=False,
        ),
    ]
