# Generated by Django 4.2.4 on 2023-09-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbucks', '0002_imagem_pedido_foto_produto_foto_usuario_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='imagem',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='prduto/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
