# Generated by Django 4.2.5 on 2023-09-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbucks', '0003_categoria_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='produtos'),
        ),
    ]
