# Generated by Django 4.2.4 on 2023-09-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbucks', '0003_remove_pedido_foto_remove_produto_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='Usuário', max_length=255),
        ),
    ]
