# Generated by Django 4.2.5 on 2023-09-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbucks', '0004_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios'),
        ),
    ]
