# Generated by Django 4.2.5 on 2023-09-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbucks', '0005_usuario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(choices=[(1, 'Carrinho'), (2, 'Realizado'), (3, 'Pago'), (4, 'Entregue')], default=1),
        ),
    ]
