# Generated by Django 4.2.5 on 2023-09-19 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbucks', '0006_alter_pedido_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='items_pedidos',
            field=models.ManyToManyField(through='ifbucks.ItemPedido', to='ifbucks.produto'),
        ),
        migrations.AddField(
            model_name='tipopessoa',
            name='cargo',
            field=models.CharField(choices=[('1', 'Cliente'), ('2', 'Garçom'), ('3', 'Cozinheiro'), ('4', 'Gerente')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='hora_pedido',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tipopessoa',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='TipoProduto',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ifbucks.mesa'),
        ),
    ]
