# Generated by Django 4.2.5 on 2023-09-19 16:01

from django.db import migrations, models
import django.db.models.deletion
import ifbucks.models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbucks', '0007_mesa_pedido_items_pedidos_tipopessoa_cargo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='produto_id',
            new_name='produto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='ifbucks.usuario'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='ifbucks.mesa'),
        ),
        migrations.AlterField(
            model_name='tipopessoa',
            name='cargo',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Garçom', 'Garçom'), ('Cozinheiro', 'Cozinheiro'), ('Gerente', 'Gerente')], default='Cliente', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=ifbucks.models.user_image_upload_to),
        ),
    ]
