# Generated by Django 4.2.5 on 2023-09-19 16:19

from django.db import migrations, models
import ifbucks.models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbucks', '0008_rename_pedido_id_itempedido_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipopessoa',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Garçom', 'Garçom'), ('Cozinheiro', 'Cozinheiro'), ('Gerente', 'Gerente')], default='Cliente', max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=ifbucks.models.produto_image_upload_to),
        ),
        migrations.DeleteModel(
            name='TipoPessoa',
        ),
    ]
