# Generated by Django 4.2.5 on 2023-09-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbucks', '0009_remove_usuario_tipopessoa_usuario_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pedido',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_pedido', to='ifbucks.pedido'),
        ),
    ]
