# Generated by Django 4.2.5 on 2023-09-20 12:27

from django.db import migrations, models
import django.db.models.deletion
import ifbucks.models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbucks', '0010_usuario_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Carrinho',
                'verbose_name_plural': 'Carrinhos',
            },
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='items_pedidos',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pedido',
            name='entregue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ifbucks.produto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='ifbucks.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.FileField(blank=True, upload_to=ifbucks.models.produto_image_upload_to),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to=ifbucks.models.user_image_upload_to),
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='items_pedidos',
            field=models.ManyToManyField(through='ifbucks.Pedido', to='ifbucks.produto'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrinhos', to='ifbucks.mesa'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrinhos', to='ifbucks.usuario'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='carrinho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='ifbucks.carrinho'),
        ),
    ]
