# Generated by Django 4.2.5 on 2023-09-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbucks', '0011_carrinho_remove_pedido_items_pedidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='pedido',
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrinhos', to='ifbucks.mesa', unique=True),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
