# Generated by Django 4.2.5 on 2023-09-20 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbucks', '0012_remove_usuario_pedido_alter_carrinho_mesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos', to='ifbucks.mesa', unique=True),
        ),
    ]
